[package]
name = "intcode"
version = "0.2.0"
authors = ["Guido Knips <guido.knips@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
